/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardVoiceRouteImport } from './routes/dashboard.voice'
import { Route as DashboardStudyPlanRouteImport } from './routes/dashboard.study-plan'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardImportRouteImport } from './routes/dashboard.import'
import { Route as DashboardCalendarRouteImport } from './routes/dashboard.calendar'
import { Route as DashboardAskRouteImport } from './routes/dashboard.ask'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardVoiceRoute = DashboardVoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStudyPlanRoute = DashboardStudyPlanRouteImport.update({
  id: '/study-plan',
  path: '/study-plan',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardImportRoute = DashboardImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCalendarRoute = DashboardCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAskRoute = DashboardAskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/ask': typeof DashboardAskRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/import': typeof DashboardImportRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/study-plan': typeof DashboardStudyPlanRoute
  '/dashboard/voice': typeof DashboardVoiceRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/ask': typeof DashboardAskRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/import': typeof DashboardImportRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/study-plan': typeof DashboardStudyPlanRoute
  '/dashboard/voice': typeof DashboardVoiceRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/ask': typeof DashboardAskRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/import': typeof DashboardImportRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/study-plan': typeof DashboardStudyPlanRoute
  '/dashboard/voice': typeof DashboardVoiceRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/dashboard/analytics'
    | '/dashboard/ask'
    | '/dashboard/calendar'
    | '/dashboard/import'
    | '/dashboard/settings'
    | '/dashboard/study-plan'
    | '/dashboard/voice'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/dashboard/analytics'
    | '/dashboard/ask'
    | '/dashboard/calendar'
    | '/dashboard/import'
    | '/dashboard/settings'
    | '/dashboard/study-plan'
    | '/dashboard/voice'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/dashboard/analytics'
    | '/dashboard/ask'
    | '/dashboard/calendar'
    | '/dashboard/import'
    | '/dashboard/settings'
    | '/dashboard/study-plan'
    | '/dashboard/voice'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/voice': {
      id: '/dashboard/voice'
      path: '/voice'
      fullPath: '/dashboard/voice'
      preLoaderRoute: typeof DashboardVoiceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/study-plan': {
      id: '/dashboard/study-plan'
      path: '/study-plan'
      fullPath: '/dashboard/study-plan'
      preLoaderRoute: typeof DashboardStudyPlanRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/import': {
      id: '/dashboard/import'
      path: '/import'
      fullPath: '/dashboard/import'
      preLoaderRoute: typeof DashboardImportRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/calendar': {
      id: '/dashboard/calendar'
      path: '/calendar'
      fullPath: '/dashboard/calendar'
      preLoaderRoute: typeof DashboardCalendarRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ask': {
      id: '/dashboard/ask'
      path: '/ask'
      fullPath: '/dashboard/ask'
      preLoaderRoute: typeof DashboardAskRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardAskRoute: typeof DashboardAskRoute
  DashboardCalendarRoute: typeof DashboardCalendarRoute
  DashboardImportRoute: typeof DashboardImportRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardStudyPlanRoute: typeof DashboardStudyPlanRoute
  DashboardVoiceRoute: typeof DashboardVoiceRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardAskRoute: DashboardAskRoute,
  DashboardCalendarRoute: DashboardCalendarRoute,
  DashboardImportRoute: DashboardImportRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardStudyPlanRoute: DashboardStudyPlanRoute,
  DashboardVoiceRoute: DashboardVoiceRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
